=== naturalvision/probostitcher/probostitcher/specs_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "inputs": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "filename": {
            "type": "string"
          },
          "streamname": {
            "type": "string"
          }
        },
        "required": ["filename", "streamname"]
      }
    },
    "output_start": {
      "type": "integer"
    },
    "output_duration": {
      "type": "integer"
    },
    "output_framerate": {
      "type": "integer"
    },
    "output_size": {
      "type": "object",
      "properties": {
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      },
      "required": ["width", "height"]
    },
    "milestones": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "timestamp": {
              "type": "integer"
            },
            "videos": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "streamname": {
                      "type": "string"
                    },
                    "x": {
                      "type": "integer"
                    },
                    "y": {
                      "type": "integer"
                    },
                    "width": {
                      "type": "integer"
                    },
                    "height": {
                      "type": "integer"
                    }
                  },
                  "required": ["streamname"]
                }
              ]
            }
          }
        }
      ]
    }
  },
  "required": [
    "inputs",
    "output_start",
    "output_duration",
    "output_framerate",
    "output_size",
    "milestones"
  ]
}

=== naturalvision/probostitcher/tests/test-files/example2.json
{
  "inputs": [
    {
      "filename": "1599816201-2020-09-11__11:23:21.webm",
      "start": 1599816201990209,
      "streamname": "daniel"
    },
    {
      "filename": "1599816217-2020-09-11__11:23:37.webm",
      "start": 1599816217956118,
      "streamname": "silvio"
    },
    {
      "filename": "1599816241-2020-09-11__11:24:01.webm",
      "start": 1599816241960255,
      "streamname": "screenshare"
    }
  ],
  "output_start": 1599816231990209,
  "output_duration": 50,
  "output_framerate": 25,
  "output_size": { "width": 300, "height": 200 },
  "milestones": [
    {
      "timestamp": 0,
      "videos": [
        {
          "streamname": "screenshare"
        },
        {
          "streamname": "silvio",
          "x": 200,
          "y": 100,
          "width": 100,
          "height": 100
        }
      ]
    }
  ]
}
